---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: react
  name: reactt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactt
  template:
    metadata:
      labels:
        app: reactt
    spec:
      containers:
        - name: notes-app
          image: anshuman123abc/notes-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: react-serv
  labels:
    app: react-serv
spec:
  selector:
    app: reactt
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 31515
  type: NodePort
